# Generated by Django 4.2.3 on 2023-09-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LevelStorage',
        ),
    ]
