# Generated by Django 4.2.3 on 2023-09-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_delete_levelstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DamID', models.IntegerField()),
                ('Level', models.FloatField()),
                ('Storage', models.FloatField()),
            ],
        ),
    ]
