# Generated by Django 4.2.3 on 2023-09-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0004_alter_schdrwldata_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schdrwldata',
            unique_together={('Date', 'StateID')},
        ),
    ]
