# Generated by Django 4.2.3 on 2023-09-21 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0005_alter_schdrwldata_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LevelStorageData',
        ),
        migrations.AlterField(
            model_name='centralsectordata',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='schdrwldata',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
