# Generated by Django 4.2.3 on 2023-09-21 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0006_delete_levelstoragedata_alter_centralsectordata_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflowsDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReservoirID', models.IntegerField()),
                ('Name', models.CharField(default='', max_length=30)),
                ('Type', models.CharField(default='', max_length=30)),
                ('DamName', models.CharField(default='', max_length=30)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
