# Generated by Django 4.2.3 on 2023-10-03 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0009_levelstoragedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherandOtherParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WID', models.IntegerField()),
                ('Name', models.CharField(default='', max_length=30)),
                ('Type', models.CharField(default='', max_length=30)),
                ('Value', models.CharField(default='', max_length=30)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
