# Generated by Django 4.2.3 on 2023-10-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0011_coalparticulars_wagonparticulars'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanddata',
            name='GenStationName',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='demanddata',
            name='GenType',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='demanddata',
            name='InstalledCap',
            field=models.FloatField(default=0),
        ),
    ]
