# Generated by Django 4.2.3 on 2023-10-28 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0012_demanddata_genstationname_demanddata_gentype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxDemandCityandSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('MaxDemand', models.FloatField()),
                ('Time', models.TimeField()),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'unique_together': {('Date', 'PID')},
            },
        ),
    ]
